// <auto-generated />
using System;
using Datasource.Socium.Ef.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datasource.Socium.Ef.Migrations
{
    [DbContext(typeof(DbContextSocium))]
    partial class DbContextSociumModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoomId" }, "IX_Chats_RoomId");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatId", "CreatedAt" }, "IX_Messages_ChatId_CreatedAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatId", "UserId" }, "IX_Participants_ChatId_UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Participants_UserId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MessageId", "UserId" }, "IX_Recipients_MessageId_UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Recipients_UserId");

                    b.ToTable("Recipients", (string)null);
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Rooms_Name")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Sender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MessageId" }, "IX_Senders_MessageId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Senders_UserId");

                    b.ToTable("Senders", (string)null);
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Login" }, "IX_Users_Login")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Chat", b =>
                {
                    b.HasOne("Datasource.Socium.Ef.Models.Room", "Room")
                        .WithMany("Chats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Message", b =>
                {
                    b.HasOne("Datasource.Socium.Ef.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Participant", b =>
                {
                    b.HasOne("Datasource.Socium.Ef.Models.Chat", "Chat")
                        .WithMany("Participants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datasource.Socium.Ef.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Recipient", b =>
                {
                    b.HasOne("Datasource.Socium.Ef.Models.Message", "Message")
                        .WithMany("Recipients")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datasource.Socium.Ef.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Sender", b =>
                {
                    b.HasOne("Datasource.Socium.Ef.Models.Message", "Message")
                        .WithOne("Sender")
                        .HasForeignKey("Datasource.Socium.Ef.Models.Sender", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datasource.Socium.Ef.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Message", b =>
                {
                    b.Navigation("Recipients");

                    b.Navigation("Sender")
                        .IsRequired();
                });

            modelBuilder.Entity("Datasource.Socium.Ef.Models.Room", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
